name: Windows Msys2 64bit (msvcrt,ucrt) gcc build and test

on: [push]

jobs:
  windows-build-and-test-golang:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        OS: ["windows-2019", "windows-2022"]
        CC: ["gcc"]
        ENVIRONMENT: ["UCRT64", "MINGW64"] # https://www.msys2.org/docs/environments/
        go-version: ["1.22.x"]
        hash:
          - sha2
          - shake
          - haraka
        size:
          - 128
          - 192
          - 256
        option:
          - s
          - f
        thash:
          - simple
          - robust
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Set up Msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.ENVIRONMENT }}
          install: >-
            base-devel
            clang
            gcc
            git
            make
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-go
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-go
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-toolchain
            openssl-devel

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Gather runtime environment
        shell: msys2 {0}
        run: |
         echo ${{ matrix.ENVIRONMENT }}
         uname -a
         bash --version
         ${{ matrix.CC }} -v

      - name: Build ref
        shell: msys2 {0}
        run: |
          export CC=${{ matrix.CC }}
          make -C ref HASH=${{ matrix.hash }} THASH=${{ matrix.thash }} clean
          make -C ref THASH=${{ matrix.thash }} PQCgenKAT_sign

      - name: Test ref
        shell: msys2 {0}
        run: |
          export CC=${{ matrix.CC }}
          make -C ref HASH=${{ matrix.hash }} THASH=${{ matrix.thash }} PARAMS=sphincs-${{ matrix.hash }}-${{ matrix.size }}${{ matrix.option }} tests
          make -C ref HASH=${{ matrix.hash }} THASH=${{ matrix.thash }} PARAMS=sphincs-${{ matrix.hash }}-${{ matrix.size }}${{ matrix.option }} test
