name: Tests golang bindings for ref implementation

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ["ubuntu-latest", "macos-latest"]
        go-version: ["1.20"]
        hash:
          - sha2
          - shake
          - haraka
        size:
          - 128
          - 192
          - 256
        option:
          - s
          - f
        thash:
          - simple
          - robust
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run go test
        run: |
          cd ref/ && go test --tags=sphincs_${{ matrix.hash }}_${{ matrix.size }}${{ matrix.option }} -v ./...

#  vim: set ft=yaml ts=2 sw=2 et :
